version: '3.8'
services:
  app:
    build: .
    image: foursales-ecommerce:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Str0ngP@ssw0rd!
      JWT_SECRET: SeuJWTSecretAqui
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ecommerce-db
    environment:
      MYSQL_ROOT_PASSWORD: Str0ngP@ssw0rd!
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
    driver: local